const POSTS_FILTER_ALL = `POSTS_FILTER_ALL`;
const POSTS_FILTER_COMPLETED = `POSTS_FILTER_COMPLETED`;
const POSTS_FILTER_PROGRESS = `POSTS_FILTER_PROGRESS`;

export { POSTS_FILTER_ALL, POSTS_FILTER_COMPLETED, POSTS_FILTER_PROGRESS };
